import {
  Briefcase,
  MapPin,
  Mail,
  Smartphone,
  GraduationCap,
  BookOpen,
  School,
  Code2,
  LayoutTemplate,
  Wrench,
  Rocket,
  Database,
  Brain,
  Server,
  Monitor,
  Sparkles,
  Bookmark,
  Gamepad2,
  CloudSun,
  ListChecks,
  TrendingUp,
  Video,
  Terminal,
  Coffee,
  Cloud,
  BarChart2,
  Download,
  ExternalLink,
  BookText,
  X,
  ChevronUp,
  UserCheck,
  Phone,
} from "lucide-react";
import { HackerRankIcon, GithubIcon, LinkedinIcon } from "./icons/CustomIcons";

/* Maps the plain string names used in src/data/portfolioData.js
   to an actual icon component. Add new entries here as needed. */
const iconMap = {
  briefcase: Briefcase,
  "map-pin": MapPin,
  mail: Mail,
  smartphone: Smartphone,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  school: School,
  "code-2": Code2,
  "layout-template": LayoutTemplate,
  wrench: Wrench,
  rocket: Rocket,
  database: Database,
  brain: Brain,
  server: Server,
  monitor: Monitor,
  sparkles: Sparkles,
  bookmark: Bookmark,
  "gamepad-2": Gamepad2,
  "cloud-sun": CloudSun,
  "list-checks": ListChecks,
  "trending-up": TrendingUp,
  video: Video,
  terminal: Terminal,
  coffee: Coffee,
  cloud: Cloud,
  "bar-chart-2": BarChart2,
  download: Download,
  "external-link": ExternalLink,
  "book-text": BookText,
  x: X,
  "chevron-up": ChevronUp,
  "user-check": UserCheck,
  phone: Phone,
  github: GithubIcon,
  linkedin: LinkedinIcon,
  hackerrank: HackerRankIcon,
};

export default function Icon({ name, ...props }) {
  const Component = iconMap[name];
  if (!Component) return null;
  return <Component {...props} />;
}
